In [55]:
X[0:2]=9
X

tensor([[ 9.,  9.,  9.,  9.],
        [ 9.,  9.,  9.,  9.],
        [ 8.,  9., 10., 11.]])

In [44]:
x[-1]

tensor([ 8.,  9., 10., 11.])

In [42]:
X.sum( )

tensor(66.)

In [41]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [39]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [25]:
torch.exp (y)

tensor([7.3891, 7.3891, 7.3891, 7.3891])

In [20]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [30]:
torch.tensor ([[0,1,2,3],[2,3,4,5],[3,4,5,6]])

tensor([[0, 1, 2, 3],
        [2, 3, 4, 5],
        [3, 4, 5, 6]])

In [18]:
torch.randn( 3,4)

tensor([[-0.0586,  0.1488,  0.0496,  1.9237],
        [-0.4886,  0.2912, -0.3170,  0.4963],
        [-0.7293, -1.0181,  0.8353, -1.2747]])

In [16]:
torch.ones ( 2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [15]:
torch.zeros ( 2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
x = x.reshape (3,4) 
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
x.numel() 

12

In [8]:
x.shape

torch.Size([12])

In [7]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
import torch
